runtime: nodejs10

instance_class: F1

env_variables:
  BUCKET_NAME: 'example-gcs-bucket'
  POSTGRES_HOST: pgsql.agileasyapp.com.br
  NODE_ENV: development
  POSTGRES_PASSWORD: severino4565
  POSTGRES_USER: agileasyapp
  POSTGRES_DB: agileasyapp
  POSTGRES_PORT: 5432
  MERCHANT_ID: 909e9c4c-00cb-4cc7-aec3-e61eb2ca517a
  MERCHANT_KEY: ULXTZOHMBWJYPLPOLJDGYXKLVPDTKSFUYVRJTUWW
  SANDBOX: true
  DEBUG: true
  PORT: 8080
  HOST: 0.0.0.0

automatic_scaling:
  min_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic # default value
  max_pending_latency: 2000ms
  max_concurrent_requests: 30
  target_throughput_utilization: 0.8
  target_cpu_utilization: 0.8
